version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_prisma
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vocab_learn_track
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
